### ISSUE TITLE
Compile error in PrinterService.cs: cannot implicitly convert string to MediaCol

### ISSUE THREAD

**Issue by dipique** [danielklecha/SharpIppNextServer#3]
When compiling the project, I see the following error:
```
...\SharpIppNextServer\Services\PrinterService.cs(344,31): error CS0029: Cannot implicitly convert type 'string' to 'SharpIpp.Protocol.Models.MediaCol'
```

This is the line of code it's referring to:
```
MediaColDefault = !IsRequired(PrinterAttribute.MediaDefault) ? null : options.Media.FirstOrDefault(),
```

This is because `options.Media` is a string array, but `MediaColDefault` has the `MediaCol` type. I believe two changes need to be made. The `IsRequired` reference probably needs to point to `PrinterAttribute.MediaColDefault` instead of `MediaDefault`, and of course a valid value needs to be assigned. I'd put in a PR but I'm not sure how to get a valid value for `MediaColDefault`.

**Comment by danielklecha** [comment]
@dipique I added new commit. Please check it.

**Comment by dipique** [comment]
Worked like a charm, thank you @danielklecha!
